import { LegalPage } from "@/components/legal-page";

export const metadata = { title: "Terms of Service — PolyGlot Code-Lab" };

export default function TermsPage() {
  return (
    <LegalPage title="Terms of Service" updated="October 2026">
      <p>
        PolyGlot Code-Lab is a prototype built for Nexathon (Track 04 &amp;
        Track 05). It is provided as-is, without warranties of any kind.
      </p>
      <p>
        Explanations and bug reports are generated by an AI model and can be
        wrong. Review everything before relying on it, and never ship generated
        fixes without testing them.
      </p>
      <p>
        You are responsible for the code you submit. Do not submit code you
        don&apos;t have the right to share, or content that is unlawful.
      </p>
    </LegalPage>
  );
}